name: CV Quality Check

on:
  push:
    branches:
      - main
      - feat/version
  pull_request:
    branches:
      - main

jobs:
  check-cv:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y exiftool poppler-utils

      - name: Check PDF exists
        run: |
          test -f CV_SDELAIGUE_FR.pdf

      - name: Check PDF size
        run: |
          SIZE=$(stat -c%s CV_SDELAIGUE_FR.pdf)
          echo "PDF size: $SIZE bytes"
          test $SIZE -lt 2000000

      - name: Extract PDF metadata
        run: |
          exiftool CV_SDELAIGUE_FR.pdf

      - name: Check PDF pages
        run: |
          pdfinfo CV_SDELAIGUE_FR.pdf | grep Pages

      - name: Check HTML
        run: |
          test -f index.html
